/*
 * generated by Xtext
 */
package my.mavenized.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HeroLanguageUiModule extends my.mavenized.ui.AbstractHeroLanguageUiModule {
	public HeroLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
