/*
 * generated by Xtext 2.23.0
 */
package my.mavenized.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HeroLanguageUiModule extends AbstractHeroLanguageUiModule {

	public HeroLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
