/*
 * generated by Xtext
 */
package my.mavenized.ui.contentassist

import my.mavenized.ui.contentassist.AbstractHeroLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HeroLanguageProposalProvider extends AbstractHeroLanguageProposalProvider {
}
