/*
 * generated by Xtext 2.23.0
 */
package my.mavenized;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HeroLanguageStandaloneSetup extends HeroLanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new HeroLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
