/*
 * generated by Xtext
 */
package my.mavenized;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HeroLanguageRuntimeModule extends my.mavenized.AbstractHeroLanguageRuntimeModule {

}
