/*
 * generated by Xtext 2.11.0.RC2
 */
package my.mavenized


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class HeroLanguageRuntimeModule extends AbstractHeroLanguageRuntimeModule {
}
