/*
 * generated by Xtext 2.11.0.RC2
 */
package my.mavenized


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HeroLanguageStandaloneSetup extends HeroLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new HeroLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
