/*
 * generated by Xtext 2.23.0
 */
package my.mavenized.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import my.mavenized.HeroLanguageRuntimeModule;
import my.mavenized.HeroLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HeroLanguageIdeSetup extends HeroLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HeroLanguageRuntimeModule(), new HeroLanguageIdeModule()));
	}
	
}
